# Generated by Django 4.1.3 on 2022-11-09 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racing_calendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dataTime',
            new_name='dateTime',
        ),
    ]
